# Generated by Django 4.2.1 on 2023-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('mid', models.DecimalField(decimal_places=4, max_digits=6)),
                ('table', models.CharField(max_length=1)),
                ('no', models.CharField(max_length=20)),
                ('effectiveDate', models.DateField()),
            ],
        ),
    ]
