# Generated by Django 4.2.1 on 2023-05-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rates',
            new_name='Rate',
        ),
    ]
